[package]

name         = "libproteus"
version      = "0.0.1"
authors      = ["Toralf Wittner <tw@dtex.org>", "Roman S. Borschel <roman@pkaboo.org>"]
description  = "Axolotl protocol implementation"
homepage     = "https://github.com/twittner/proteus"
repository   = "git@github.com:twittner/proteus.git"
license      = "MPL-2.0"

[dependencies]
bincode         = "> 0.0.9"
byteorder       = "> 0.2.0"
rustc-serialize = "> 0.3.0"
sodiumoxide     = "> 0.0.1"

[dependencies.hkdf]
git = "https://github.com/twittner/hkdf"
