[package]

name         = "proteus"
version      = "0.3.0"
authors      = ["Toralf Wittner <tw@dtex.org>", "Roman S. Borschel <roman@pkaboo.org>"]
description  = "Axolotl protocol implementation"
homepage     = "https://github.com/twittner/proteus"
repository   = "git@github.com:twittner/proteus.git"
license      = "MPL-2.0"

[dependencies]
byteorder   = ">  0.2.0"
cbor-codec  = ">= 0.1.0"
libc        = ">  0.1.0"
sodiumoxide = ">= 0.0.8"

[dependencies.hkdf]
git = "https://github.com/twittner/hkdf"
