[package]

name         = "proteus"
version      = "0.1.0"
authors      = ["Toralf Wittner <tw@dtex.org>", "Roman S. Borschel <roman@pkaboo.org>"]
description  = "Axolotl protocol implementation"
homepage     = "https://github.com/twittner/proteus"
repository   = "git@github.com:twittner/proteus.git"
license      = "MPL-2.0"

[dependencies]
byteorder       = "> 0.2.0"
rustc-serialize = "> 0.3.0"

[dependencies.sodiumoxide]
git    = "https://github.com/twittner/sodiumoxide"
branch = "toml"

[dependencies.hkdf]
git    = "https://github.com/twittner/hkdf"
branch = "toml"

[dependencies.cbor-codec]
git = "https://github.com/twittner/cbor-codec"
